cc_binary(
  name = '1_binInsert',
  srcs = '1_binInsert.cc',
)

cc_binary(
  name = '2_printBin',
  srcs = '2_printBin.cc',
)

cc_binary(
  name = '3_getCloseNumber',
  srcs = '3_getCloseNumber.cc',
)

cc_binary(
  name = '5_calcCost',
  srcs = '5_calcCost.cc',
)

cc_binary(
  name = '6_exchangeOddEven',
  srcs = '6_exchangeOddEven.cc',
)

cc_binary(
  name = '7_findMissing',
  srcs = '7_findMissing.cc',
)

cc_binary(
  name = '8_renderPixel',
  srcs = '8_renderPixel.cc',
)
