cc_binary(
  name = '1_countWays',
  srcs = '1_countWays.cc',
)

cc_binary(
  name = '2_countWaysRobot',
  srcs = '2_countWaysRobot.cc',
)

cc_binary(
  name = '2_countWaysRobot2',
  srcs = '2_countWaysRobot2.cc',
)

cc_binary(
  name = '3_findMagicIndex',
  srcs = '3_findMagicIndex.cc',
)

cc_binary(
  name = '3_findMagicIndex2',
  srcs = '3_findMagicIndex2.cc',
)

cc_binary(
  name = '4_getSubsets',
  srcs = '4_getSubsets.cc',
)

cc_binary(
  name = '5_getPermutation',
  srcs = '5_getPermutation.cc',
)

cc_binary(
  name = '6_chkParenthesis',
  srcs = '6_chkParenthesis.cc',
)
