cc_binary(
  name = '1_countWays',
  srcs = '1_countWays.cc',
)

cc_binary(
  name = '2_countWaysRobot',
  srcs = '2_countWaysRobot.cc',
)

cc_binary(
  name = '3_countWaysRobot2',
  srcs = '3_countWaysRobot2.cc',
)

cc_binary(
  name = '4_findMagicIndex',
  srcs = '4_findMagicIndex.cc',
)

cc_binary(
  name = '5_findMagicIndex2',
  srcs = '5_findMagicIndex2.cc',
)

cc_binary(
  name = '6_getSubsets',
  srcs = '6_getSubsets.cc',
)
