cc_binary(
  name = 'type_name',
  srcs = [
    'type_name.cc',
  ],
  deps = [
  ]
)

cc_binary(
  name = 'forward',
  srcs = [
    'forward.cc',
  ],
  deps = [
  ]
)

cc_binary(
  name = 'func_wrapper',
  srcs = [
    'func_wrapper.cc',
  ],
  deps = [
  ]
)
