cc_binary(
  name = '1_Joseph1',
  srcs = '1_Joseph1.cc',
)

cc_binary(
  name = '1_Joseph2',
  srcs = '1_Joseph2.cc',
)

cc_binary(
  name = '2_sortStrings',
  srcs = '2_sortStrings.cc',
)

cc_binary(
  name = '3_findElement',
  srcs = '3_findElement.cc',
)

cc_binary(
  name = '5_findString',
  srcs = '5_findString.cc',
)

cc_binary(
  name = '6_findElement',
  srcs = '6_findElement.cc',
)

cc_binary(
  name = '7_getHeight',
  srcs = '7_getHeight.cc',
)

cc_binary(
  name = '8_getRankOfNumber',
  srcs = '8_getRankOfNumber.cc',
)
