cc_binary(
  name = '1_antsCollision',
  srcs = '1_antsCollision.cc',
)

cc_binary(
  name = '2_checkCrossLine',
  srcs = '2_checkCrossLine.cc',
)

cc_binary(
  name = '3_calc',
  srcs = '3_calc.cc',
)

cc_binary(
  name = '4_getBipartition',
  srcs = '4_getBipartition.cc',
)
