cc_binary(
  name = '2_antsCollision',
  srcs = '2_antsCollision.cc',
)

cc_binary(
  name = '3_checkCrossLine',
  srcs = '3_checkCrossLine.cc',
)

cc_binary(
  name = '4_calc',
  srcs = '4_calc.cc',
)

cc_binary(
  name = '5_getBipartition',
  srcs = '5_getBipartition.cc',
)

cc_binary(
  name = '6_getLine',
  srcs = '6_getLine.cc',
)
