cc_binary(
  name = 'sort_bubble',
  srcs = [
    'sort_bubble.cc',
  ],
  deps = [
  ]
)

cc_binary(
  name = 'sort_select',
  srcs = [
    'sort_select.cc',
  ],
  deps = [
  ]
)

cc_binary(
  name = 'sort_insert',
  srcs = [
    'sort_insert.cc',
  ],
  deps = [
  ]
)

cc_binary(
  name = 'sort_merge',
  srcs = [
    'sort_merge.cc',
  ],
  deps = [
  ]
)

cc_binary(
  name = 'sort_quik',
  srcs = [
    'sort_quick.cc',
  ],
  deps = [
  ]
)
