cc_binary(
  name = '3_buildMinimalBST',
  srcs = '3_buildMinimalBST.cc',
)

cc_binary(
  name = '4_getTreeLevel',
  srcs = '4_getTreeLevel.cc',
)

cc_binary(
  name = '5_checkBST',
  srcs = '5_checkBST.cc',
)
