cc_binary(
  name = '1_different',
  srcs = [
    '1_different.cc',
  ],
)

cc_binary(
  name = '2_reverse',
  srcs = [
    '2_reverse.cc',
  ],
)

cc_binary(
  name = '3_same',
  srcs = [
    '3_same.cc',
  ],
)

cc_binary(
  name = '4_replacement',
  srcs = [
    '4_replacement.cc',
  ],
)

cc_binary(
  name = '5_zipper',
  srcs = [
    '5_zipper.cc',
  ],
)
